### ISSUE TITLE
Erln8 does not handle paths with spaces

### ISSUE THREAD

**Issue by nox** [metadave/erln8#14]
Not that I care that much, but [shell commands with unescaped arguments](https://github.com/metadave/erln8/blob/0895d95f4bfcfcaf4b17f1e5934385c14eee08ec/erln8.c#L1005-L1025) always make me worry. Any space in ERLN8_HOME will make the tool crash. Other arguments might be subject to such bugs too.

**Comment by metadave** [comment]
wont fix, see comment above.
