### ISSUE TITLE
erln8 assumes GNU compiler & make by default

### ISSUE THREAD

**Issue by dch** [metadave/erln8#15]
It's possible to override the compiler using environment variables, but not make. On FreeBSD and other systems, OTP needs to be built with `gmake` not `make`.

**Comment by metadave** [comment]
Good find, I'll take a look. Might be a few days, waiting for my daughter to be born any minute :-)

**Comment by javajolt** [comment]
I love how I find out what's going in @metadave's life via GitHub! Maybe you could augment the experience by tweeting some baby pix?

**Comment by metadave** [comment]
@dch I pushed a change to allow the `MAKE_BIN` env var to be used. Check out PR https://github.com/metadave/erln8/pull/16
and let me know if this works for you. I'll eventually test on FreeBSD, but I don't have a VM setup atm.

@javajolt nothing happening *yet*, very soon though. I'll keep you posted.

Cheers -
Dave

**Comment by metadave** [comment]
resolved by https://github.com/metadave/erln8/pull/16
