### ISSUE TITLE
symlink named 'start'?

### ISSUE THREAD

**Issue by tsloughter** [metadave/erln8#17]
Why is there a symlink to `erln8` named start? Having this in my PATH means I can't call upstart with `sudo` because it remains in the path.

**Comment by metadave** [comment]
Will check it out in a couple days.
Cheers
Dave

**Comment by metadave** [comment]
looks like it's something including with Erlang:

```
20:06:06 ~/.erln8.d/otps/quickstart_build$ find . -name "start"
./dist/lib/erlang/bin/start
./dist/lib/erlang/erts-6.1.2/bin/start
```

I naively include all executables upon install, I'll revisit soon.

**Comment by metadave** [comment]
removed `start` from symlinked executables in the latest commit. 

You can safely remove `/usr/local/bin/start` (or wherever you installed erln8 to), and run `make uninstall` followed by `make install` with the latest updates.

Sorry for the delay ;-)

Cheers -
Dave
